CREATE TABLE medicos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome          VARCHAR(255),
    email         VARCHAR(255),
    crm           VARCHAR(255),
    especialidade VARCHAR(255),
    logradouro    VARCHAR(255),
    bairro        VARCHAR(255),
    cep           VARCHAR(255),
    numero        VARCHAR(255),
    complemento   VARCHAR(255),
    cidade        VARCHAR(255),
    uf            VARCHAR(255),
    CONSTRAINT pk_medicos PRIMARY KEY (id)
);